Irina Abashidze: Homework_11 added 1 file homework_11_task1_class_book.py
eugene-okulik/IrinaA pull request #10
Opened 2024-02-26 23:12 UTC by Irina1309

2024-02-27 08:19 UTC, eugene-okulik requested changes
Остальное, кроме того, что в комменте - отлично. Давай вынесем два свойства из свойств экземпляра в свойства класса. И всё круто будет.

2024-02-27 08:19 UTC, eugene-okulik commented on homework/irina_abashidze/Homework_11/homework_11_task1_class_book.py
> +        self.reserved = reserved
По заданию нужно было, чтобы некоторые свойства быи сделаны общими для всего класса. Т.е. чтобы они не запрашивались при создании объекта, а были сразу определены для всех объектов класса. Например, материал всех книг - бумага, все книги имеют текст. Эти два свойства и можно сделать свойствами класса.

2024-02-27 11:27 UTC, Irina1309 commented
Добавила новый файл homework_11_task1_v2_class_common_prop.py,  старый файл оставила без изменений - надо его удалить?

2024-02-28 12:05 UTC, eugene-okulik commented
> Добавила новый файл homework_11_task1_v2_class_common_prop.py, старый файл оставила без изменений - надо его удалить?

Можешь не удалять, как хочешь. Но, похоже, ты забыла запушить этот новый файл ))

2024-02-28 13:04 UTC, Irina1309 commented
Да, забыла... а как мне это было видно, что файл не был запушен?

2024-02-28 13:16 UTC, eugene-okulik approved these changes

2024-02-28 13:16 UTC, merged