Irina Abashidze: Homework_13 added a new file homework_13_task1_read_file.py
eugene-okulik/IrinaA pull request #12
Opened 2024-03-02 12:26 UTC by Irina1309

2024-03-02 12:28 UTC, Irina1309 commented
Программа вывела:
2023-12-04 00:00:00.000000 никак не могу исправить эти нули... прошу помощи и подсказки, как это исправить
Saturday
264

2024-03-02 18:40 UTC, Irina1309 commented
Исправила ошибку :)

2024-03-03 08:02 UTC, eugene-okulik requested changes
Остальное, кроме того что в комменте, выглядит хорошо

2024-03-03 08:02 UTC, eugene-okulik commented on homework/irina_abashidze/Homework_13/homework_13_task1_read_file.py
> +file_path = os.path.join(base_path, "C:\\Users\\Ирина\\IrinaA\\homework\\eugene_okulik\\hw_13\\data.txt")
У меня не работает. Я на линуксе, и у меня слеши вот такие: /

2024-03-03 08:02 UTC, eugene-okulik commented on homework/irina_abashidze/Homework_13/homework_13_task1_read_file.py
> +file_path = os.path.join(base_path, "C:\\Users\\Ирина\\IrinaA\\homework\\eugene_okulik\\hw_13\\data.txt")
Да и папки Ирина у меня нет

2024-03-03 10:38 UTC, Irina1309 commented
Изменила в коде путь к файлу:
base_path = os.path.dirname(__file__)
homework_path = os.path.dirname(os.path.dirname(base_path))
eugene_file_path = os.path.join(homework_path, 'eugene_okulik', 'hw_13', 'data.txt')

2024-03-03 11:06 UTC, eugene-okulik approved these changes

2024-03-03 11:06 UTC, merged