Irina Abashidze: Homework_15 added a new file homework_15_database.py
eugene-okulik/IrinaA pull request #14
Opened 2024-03-05 00:34 UTC by Irina1309

2024-03-05 08:33 UTC, eugene-okulik requested changes
А чего половина задания закомментировано?  
Ну и смотрю, что id все ты хардкодишь, но нужно сделать так, чтобы ты студенту добавила ту группу, которая добавлена программой, книги, оценки выдала тому студенту, которого ты добавила. То есть не студенту с id 411, а студенту с тем id, с которым добавился студент в начале программы.

2024-03-06 00:44 UTC, Irina1309 commented
Исправила, отправила для проверки новый файл 
homework_15_database2.py

2024-03-06 07:48 UTC, eugene-okulik requested changes
Ни в каком месте кода ты не должна писать руками какие-то id. Ты здесь не используешь никакие данные из тех, которые были в базе до запуска программы. Программа сама создаёт все данные и пользуется ими
- Создаешь студента - получаешь его id, сохраняешь это id в переменную, потом пользуешься везде, где тебе нужен id студента
- Создаешь группу - получаешь id добавленной группы, сохраняешь в переменную и потом пользуешься везде, где тебе нужен id группы
- И так с каждой штукой, которую ты добавляешь. Если тебе нужны id оценок, предметов, уроков, то их нужно добавлять без использования `executemany`, потому что после `executemany` невозмоно получить id всех добавленных строк. Нужно добавлять всё это по одному и сохранять id в переменную.

2024-03-06 07:48 UTC, eugene-okulik commented on homework/irina_abashidze/Homework_15/homework_15_database2.py
> +print(group_id)
id студента ты получила с помощью `cursor.lastrowid`, а здесь пошла получать последнюю группу запросом. Если твоя программа - это не единственное, что сейчас работает с базой данных, то у тебя есть шанс получить чужую группу.

2024-03-06 07:48 UTC, eugene-okulik commented on homework/irina_abashidze/Homework_15/homework_15_database2.py
> +db.commit()
У тебя в переменной `group_id` есть id созданной группы, но ты им не пользуешься, а хардкодишь id 395, которое создано не во время работы программы.

2024-03-06 07:48 UTC, eugene-okulik commented on homework/irina_abashidze/Homework_15/homework_15_database2.py
> +db.commit()
И студента тебе не нужно искать по имени и фамилии, ведь у тебя есть id добавленного студента в переменной `added_student_id`

2024-03-06 07:48 UTC, eugene-okulik commented on homework/irina_abashidze/Homework_15/homework_15_database2.py
> +value FROM marks WHERE student_id = 424
Во время запуска добавился новый студент, а данные ты получаешь для студента с id 424

2024-03-06 07:48 UTC, eugene-okulik commented on homework/irina_abashidze/Homework_15/homework_15_database2.py
> +        OR (m.lesson_id IN (520, 521) AND b.id = 558)
Нужно получить данные по добавленному студенту, а не данные для занятий 518, 519, 520, 521 и книгам 557 и 558

2024-03-07 00:25 UTC, Irina1309 commented
Отправила для проверки новый файл
homework_15_database3.py
не получилось сделать выборку "Получить данные по добавленному студенту" - ошибки программа не выдает по ней, но и никаких данных по ней не распечатала

2024-03-07 07:27 UTC, eugene-okulik requested changes

2024-03-07 07:27 UTC, eugene-okulik commented on homework/irina_abashidze/Homework_15/homework_15_database3.py
> +    cursor.execute(insert_subjects_query, (subject,))
Там ниже ты получаешь идентификаторы селектом, но если есть группы, с одинаковыми данными, ты получишь не те id. Можно было сразу при добавлении их получать и складывать в список
```python
subject_ids = []
for subject in subjects:
    cursor.execute(insert_subjects_query, (subject,))
    subject_ids.append(cursor.lastrowid)
```

2024-03-07 07:27 UTC, eugene-okulik commented on homework/irina_abashidze/Homework_15/homework_15_database3.py
> +print(cursor.fetchall())
Везде всё теперь без хардкодов, а здесь в двух местах остались. Здесь всё так же как везде
```python
select_query = '''
SELECT
value FROM marks WHERE student_id = %s
'''
cursor.execute(select_query, (added_student_id,))
print(cursor.fetchall())

select_query_2 = '''
SELECT title FROM books WHERE taken_by_student_id = %s
'''
cursor.execute(select_query_2, (added_student_id,))
print(cursor.fetchall())
```

2024-03-07 10:16 UTC, Irina1309 commented
Отправила для проверки новый файл
homework_15_database4.py
Большое спасибо за дополнительные разъяснения и ответы.

2024-03-07 19:32 UTC, eugene-okulik approved these changes

2024-03-07 19:33 UTC, merged