Irina Abashidze: Homework_16 added a new file homework_16_csv.py
eugene-okulik/IrinaA pull request #15
Opened 2024-03-09 10:29 UTC by Irina1309

Программа выдает ошибку KeyError: 'Name'
но не пойму, как исправить

2024-03-09 19:09 UTC, eugene-okulik requested changes

2024-03-09 19:09 UTC, eugene-okulik commented on homework/irina_abashidze/Homework_16/homework_16_csv.py
> +csv_set = set((row['Name'], row['last']) for row in csv_data)
В csv файле есть колонка "name", но нет колонки "Name", вот и ругается.  
Хе-хе, и колонки "last" тоже нет.  
Есть шанс взорвать тебе голову, но не буду. Ты здесь в коде указала правильный путь к csv файлу, а сама, судя по всему, смотришь не в тот.
Здесь в коде ты работаешь с файлом eugene_okulik/Lesson_16/hw_data/data.csv - и это тот файл, с которым надо работать  
А смотришь в файл eugene_okulik/Lesson_16/data.csv - этот тот файл, с которым я на занятии игрался.

2024-03-09 23:28 UTC, Irina1309 commented
Добавила для проверки новый файл homework_16_csv2.py

2024-03-10 12:53 UTC, eugene-okulik approved these changes
Отлично! Заканчиваем часть про Python и следующее  задание - отчетная работа. Я выдал тебе два варианта этой отчетной работы: одно чуть упрощенное, другое - пообъемнее. Нужно выбрать одно из них.  
А если хочешь, можешь выполнить то, которое полегче, а потом как-нибудь постепенно выполнить то, что посложнее, параллельно с дальнейшим прохождением курса.  
Если будут вопросы, пиши.

2024-03-10 12:53 UTC, merged