Irina Abashidze: Homework_17_analyzer2 added a new file analyzer2.py
eugene-okulik/IrinaA pull request #17
Opened 2024-03-11 14:09 UTC by Irina1309

Первая версия второй программы analyzer2 (вариант посложнее).

2024-03-11 21:19 UTC, eugene-okulik requested changes
Прикольный подход. С такой стороны эту штуку еще не решали. И это толковый вариант - отсеивать блоки еще при формировании.  
Круто было бы еще добавить раскраску, ну или 300 символов чтобы было именно вокруг искомого текста.

2024-03-11 21:19 UTC, eugene-okulik commented on homework/irina_abashidze/Homework_17_analyzer2/analyzer2.py
> +            print(f"Файл: {result['file']}, Строка: {result['line_number']}, Текст: {result['text'][:300]}")
Здесь ты распечатываешь первые 300 символов текста, но искомый текст может в них даже не входить. Хорошо бы распечатывать 300 символов вокруг искомого текста, т.е. 150 символов до и 150 символов после.

2024-03-12 18:14 UTC, Irina1309 commented
Добавила новый файл analyzer2_3.py (добавила цвет, выводить 300 символов вокруг найденного текста, где 150 символов до и после текста), но при запуске программы текст не находит (Логи не содержат указанный текст), 
не пойму, в чем проблема.

2024-03-13 22:34 UTC, Irina1309 commented
Файл analyzer.py - программа (вариант полегче) находит указанный текст

Файл analyzer2_3.py - программа (вариант посложнее) не находит указанный текст
Запускаю программу python analyzer2_3.py C:\Users\...\homewo
rk\eugene_okulik\data\logs --text OutOfMemoryError
Программа выводит результат:
Ищем текст: 'OutOfMemoryError'
Обрабатываем файл: C:\Users\Ирина\IrinaA\homework\eugene_okulik\data\logs\rpe-api-error.2022-02-03.0.log
Обрабатываем файл: C:\Users\Ирина\IrinaA\homework\eugene_okulik\data\logs\rpe-api-error.2022-02-03.1.log
Обрабатываем файл: C:\Users\Ирина\IrinaA\homework\eugene_okulik\data\logs\rpe-api-error.2022-02-03.2.log
Обрабатываем файл: C:\Users\Ирина\IrinaA\homework\eugene_okulik\data\logs\rpe-api-error.2022-02-03.3.log
Обрабатываем файл: C:\Users\Ирина\IrinaA\homework\eugene_okulik\data\logs\rpe-api-error.2022-02-03.4.log
Обрабатываем файл: C:\Users\Ирина\IrinaA\homework\eugene_okulik\data\logs\rpe-api-error.2022-02-03.5.log
Обрабатываем файл: C:\Users\Ирина\IrinaA\homework\eugene_okulik\data\logs\rpe-api-error.2022-02-03.6.log
Обрабатываем файл: C:\Users\Ирина\IrinaA\homework\eugene_okulik\data\logs\rpe-api-error.2022-02-03.7.log
Обрабатываем файл: C:\Users\Ирина\IrinaA\homework\eugene_okulik\data\logs\rpe-api-error.2022-02-03.8.log
Обрабатываем файл: C:\Users\Ирина\IrinaA\homework\eugene_okulik\data\logs\rpe-api-error.2022-02-03.9.log
Логи не содержат указанный текст.
Но этот текст точно есть в логах.
Пожалуйста, прошу подсказать, где искать ошибку?

2024-03-14 07:27 UTC, eugene-okulik commented
> Файл analyzer.py - программа (вариант полегче) находит указанный текст
> 
> Файл analyzer2_3.py - программа (вариант посложнее) не находит указанный текст Запускаю программу python analyzer2_3.py C:\Users...\homewo rk\eugene_okulik\data\logs --text OutOfMemoryError Программа выводит результат: Ищем текст: 'OutOfMemoryError' Обрабатываем файл: C:\Users...\homework\eugene_okulik\data\logs\rpe-api-error.2022-02-03.0.log Обрабатываем файл: C:\Users...\homework\eugene_okulik\data\logs\rpe-api-error.2022-02-03.1.log Обрабатываем файл: C:\Users...\homework\eugene_okulik\data\logs\rpe-api-error.2022-02-03.2.log Обрабатываем файл: C:\Users...\homework\eugene_okulik\data\logs\rpe-api-error.2022-02-03.3.log Обрабатываем файл: C:\Users...\homework\eugene_okulik\data\logs\rpe-api-error.2022-02-03.4.log Обрабатываем файл: C:\Users...\homework\eugene_okulik\data\logs\rpe-api-error.2022-02-03.5.log Обрабатываем файл: C:\Users...\homework\eugene_okulik\data\logs\rpe-api-error.2022-02-03.6.log Обрабатываем файл: C:\Users...\homework\eugene_okulik\data\logs\rpe-api-error.2022-02-03.7.log Обрабатываем файл: C:\Users...\homework\eugene_okulik\data\logs\rpe-api-error.2022-02-03.8.log Обрабатываем файл: C:\Users...\homework\eugene_okulik\data\logs\rpe-api-error.2022-02-03.9.log Логи не содержат указанный текст.
> 
> Но этот текст точно есть в логах. Пожалуйста, прошу подсказать, где искать ошибку?

Это отличный шанс как раз научиться искать проблемы. Например, у тебя есть код `print(f"Текст '{search_text}' не найден в блоке:")` который явно не отрабатывает`. А если бы текста на было в блоках, то эта строка распечаталась бы много раз, а это значит, что это условие не отрабатывает: `if search_text and search_text not in block_text:

2024-03-15 00:44 UTC, Irina1309 commented
Внесла изменение:
    if search_text and search_text.lower().strip() not in block_text.lower().strip():
        print(f"Текст '{search_text}' не найден в блоке:")
        print(block_text)
        return
но программа текст все равно не находит.
как понять, где искать проблему?

2024-03-15 09:05 UTC, eugene-okulik reviewed
Теперь так
```
python analyzer2_3.py ../../eugene_okulik/data/logs/ --text geometries
Ищем текст: 'geometries'
Обрабатываем файл: ../../eugene_okulik/data/logs/rpe-api-error.2022-02-03.3.log
нет временной метки - 2022-02-03
Обрабатываем файл: ../../eugene_okulik/data/logs/rpe-api-error.2022-02-03.9.log
нет временной метки - 2022-02-03
Обрабатываем файл: ../../eugene_okulik/data/logs/rpe-api-error.2022-02-03.0.log
нет временной метки - 2022-02-03
Обрабатываем файл: ../../eugene_okulik/data/logs/rpe-api-error.2022-02-03.5.log
нет временной метки - 2022-02-03
Обрабатываем файл: ../../eugene_okulik/data/logs/rpe-api-error.2022-02-03.6.log
нет временной метки - 2022-02-03
Обрабатываем файл: ../../eugene_okulik/data/logs/rpe-api-error.2022-02-03.7.log
нет временной метки - 2022-02-03
Обрабатываем файл: ../../eugene_okulik/data/logs/rpe-api-error.2022-02-03.1.log
нет временной метки - 2022-02-03
Обрабатываем файл: ../../eugene_okulik/data/logs/rpe-api-error.2022-02-03.2.log
нет временной метки - 2022-02-03
Обрабатываем файл: ../../eugene_okulik/data/logs/rpe-api-error.2022-02-03.4.log
нет временной метки - 2022-02-03
Обрабатываем файл: ../../eugene_okulik/data/logs/rpe-api-error.2022-02-03.8.log
нет временной метки - 2022-02-03
Логи не содержат указанный текст.
```
И вот анализируя это "нет временной метки" смотрим на код, где это срабатывает. И видим, что время из строки ты получаешь так:
```python
timestamp_str = block[0].split()[0]
```
Если строка и начинается с даты, то ты получаешь из строки вот что: 2022-02-03, хотя вся дата это, например, 2022-02-03 00:01:13.623
потом ты полученную дату пытаешься превратить в питоновский формат с помощью
```python
timestamp = datetime.strptime(timestamp_str, "%Y-%m-%d %H:%M:%S.%f")
```
И получается, ты превращаешь дату 2022-02-03, расчитывая на то, что она в формате 2022-02-03 00:01:13.623 и в итоге ты ни одну дату никогда не превращаешь в питоновскую и каждая попытка падает с ексепшеном, который ты и перехватываешь, в итоге, блок ты всегда пропускаешь.

2024-03-15 23:13 UTC, Irina1309 commented
Внесла изменения, теперь текст находит в логах.

Но при поиске по дате, программа пишет: Ищем текст: 'None'...
Пыталась исправить,  внесла изменения в условия:
    if args.start_date is not None:
        start_date = datetime.strptime(args.start_date, "%Y-%m-%d")
    else:
        start_date = None

    if args.end_date is not None:
        end_date = datetime.strptime(args.end_date, "%Y-%m-%d")
    else:
        end_date = None

    if args.text is not None:
        search_text = args.text
    else:
        search_text = None

    if args.unwanted_text is not None:
        unwanted_text = args.unwanted_text
    else:
        unwanted_text = None
    
но проблема осталась - при поиске по дате пишет: Ищем текст: 'None'

2024-03-16 16:45 UTC, eugene-okulik approved these changes
Ура! Круто.  
Ну как тебе?  
Да, написание программ - это не то, чем занимаются автотестеры. Автотесты в целом попроще, в них не столько логики, но тоже бывают сложные моменты.  
Иногда и автотестерам бывает нужно написать каку-нибудь программку. Например, вот эта, которая в задании - это одна из моих реальных рабочих задач, которой я занимался несколько лет назад.  
По задумке, это задание тренирует скилл поиска решения каких-то задач и скилл поиска проблем в своем коде. Еще оно полезно тем, что становится понятнее откуда растут ноги у багов, которые мы находим в приложениях, которые тестируем.

2024-03-16 16:45 UTC, merged

2024-03-18 18:15 UTC, Irina1309 commented
Это самое сложное и самое интересное задание. 
Внесла изменение: 
if args.start_date is not None:
    start_date = datetime.strptime(args.start_date, "%Y-%m-%d %H:%M:%S.%f")
else:
    start_date = None

if args.end_date is not None:
    end_date = datetime.strptime(args.end_date, "%Y-%m-%d %H:%M:%S.%f")
else:
    end_date = None

Запустила:  python analyzer2_3.py C:\Users\Ирина\IrinaA\homewo
rk\eugene_okulik\data\logs --start_date '2022-02-03 00:01:13.623'

Результаты поиска:
Traceback (most recent call last):
  File "C:\Users\Ирина\IrinaA\homework\irina_abashidze\Homework_17_analyzer2\analyzer2_3.py", line 142, in <module>
    print_results(results, args.full_output)
  File "C:\Users\Ирина\IrinaA\homework\irina_abashidze\Homework_17_analyzer2\analyzer2_3.py", line 75, in print_results
    start_index = text.find(search_text)
                  ^^^^^^^^^^^^^^^^^^^^^^
TypeError: must be str, not NoneType

2024-03-18 21:43 UTC, Irina1309 commented
Внесла изменение:
def print_results(results, full_output=False):
    if results:
        print("Результаты поиска:")
        for result in results:
            text = result['text']
            # Проверяем, что text не None и search_text не None
            if text is not None and search_text is not None:
                # Находим индекс начала искомого текста
                start_index = text.find(search_text)
                # Выводим 150 символов перед искомым текстом
                start_highlight = max(0, start_index - 150)
                # Выводим 150 символов после искомого текста
                end_highlight = min(len(text), start_index + len(search_text) + 150)
                # Выделение цветом
                highlighted_text = (
                    text[start_highlight:start_index]
                    + Fore.RED
                    + text[start_index:start_index + len(search_text)]
                    + Style.RESET_ALL
                    + text[start_index + len(search_text):end_highlight]
                )
                # Выводим результат с выделением цветом
                print(f"Файл: {result['file']}, Строка: {result['line_number']}, Текст: {highlighted_text}")
            else:
                print(f"Файл: {result['file']}, Строка: {result['line_number']}, Текст: {text}")
            if full_output:
                print(text)
            print()
    else:
        print("Логи не содержат указанный текст.")

2024-03-19 09:39 UTC, eugene-okulik reviewed
Сейчас весь поиск потработал как ожидалось
```
python analyzer2_3.py ../../eugene_okulik/data/logs/ --start_date "2022-02-03 09:01:32.360" --text WARN --unwanted_text answer
```
Этот запуск вернул одну найденную строку.  
Чисто так, чтобы всё было еще идеальнее, хорошо бы писать сообщения, соответствующие запросу. Например, если я запущу поиск так:
```
python analyzer2_3.py ../../eugene_okulik/data/logs/ --start_date "2023-02-03 09:01:32.360" 
```
В логах ничего не будет найдено, но напишет мне "Логи не содержат указанный текст." Но я текст и не искал.  
Ну и еще круто было бы в конце написать сколько строк, соответствующих условиям поиска, найдено