Irina Abashidze: Homework_19 PyTest new file homework_19_test_api.py
eugene-okulik/IrinaA pull request #20
Opened 2024-03-16 14:13 UTC by Irina1309

2024-03-16 14:18 UTC, Irina1309 commented
Запуск программы: pytest homework_19_test_api.py
Результаты тестирования:
====================================================== test session starts ======================================================
platform win32 -- Python 3.12.0, pytest-8.1.1, pluggy-1.4.0
rootdir: C:\Users\ирина\IrinaA\homework\irina_abashidze\Homework_19
collected 4 items

homework_19_test_api.py ...F                                                                                               [100%]

=========================================================== FAILURES ============================================================ 
______________________________________________________ test_delete_object _______________________________________________________ 

created_object_id = 'ff8081818e21ce2d018e47998f5c2804'

    def test_delete_object(created_object_id):
        base_url = f"https://api.restful-api.dev/objects/{created_object_id}"

        response = requests.delete(base_url)

        assert response.status_code == 200, f"Failed to delete object. Unexpected status code: {response.status_code}"
>       assert response.json() == {}, "Delete response data is not empty"
E       AssertionError: Delete response data is not empty
E       assert {'message': '...een deleted.'} == {}
E
E         Left contains 1 more item:
E         {'message': 'Object with id = ff8081818e21ce2d018e47998f5c2804 has been '
E                     'deleted.'}
E         Use -v to get more diff

homework_19_test_api.py:104: AssertionError
--------------------------------------------------- Captured stdout teardown ---------------------------------------------------- 
Testing completed
==================================================== short test summary info ==================================================== 
FAILED homework_19_test_api.py::test_delete_object - AssertionError: Delete response data is not empty
================================================= 1 failed, 3 passed in 11.92s ==================================================

2024-03-16 17:38 UTC, eugene-okulik requested changes
Еще не хватает некоторых пунктов из задания:

> Тест на создание объекта оформите так, чтобы он тестировал создание трёх разных объектов с помощью parametrize

> Сделайте так, чтобы перед каждым тестом распечатывалось "before test", а после каждого теста - "after test"

> Пометьте 1 тест как "critical", а один тест как "medium". Сделайте так, чтобы при выполнении тестов в терминале не было ошибок и ворнингов.

2024-03-16 17:38 UTC, eugene-okulik commented on homework/irina_abashidze/Homework_19/homework_19_test_api.py
> +    assert response.json() == {}, "Delete response data is not empty"
А почему ты в этом тесте ожидаешь что ответ придет пустой, если эта апишка при удалении в ответ шлет

> {'message': 'Object with id = ff8081818e21ce2d018e485169642891 has been deleted.'}

?

2024-03-16 17:38 UTC, eugene-okulik commented on homework/irina_abashidze/Homework_19/homework_19_test_api.py
> +def test_create_object(name="New Object", attribute1="value1", attribute2="value2"):
То, что указано в параметрах с дефолтными значениями, можно было сделать переменными самой тестовой фнукции. Так было бы более читаемо.

2024-03-17 00:51 UTC, Irina1309 commented
Запуск программы: pytest homework_19_test_api2.py
Результаты тестирования:
====================================================== test session starts ======================================================
platform win32 -- Python 3.12.0, pytest-8.1.1, pluggy-1.4.0
rootdir: C:\Users\ирина\IrinaA\homework\irina_abashidze\Homework_19
collected 6 items

homework_19_test_api2.py ......                                                                                            [100%]

====================================================== 6 passed in 11.09s =======================================================

2024-03-17 16:35 UTC, eugene-okulik approved these changes

2024-03-17 16:35 UTC, eugene-okulik commented on homework/irina_abashidze/Homework_19/conftest.py
> +    config.addinivalue_line("markers", "medium: Marks a test as medium.")
Ну да, можно и так, но обычно создают pytest.ini

2024-03-17 16:35 UTC, merged