Irina abashidze homework 17 logs analyzer 2
eugene-okulik/IrinaA pull request #21
Opened 2024-03-18 21:46 UTC by Irina1309

2024-03-18 21:56 UTC, Irina1309 commented
Запуск программы: python analyzer2_3.py C:\Users\Ирина\IrinaA\homewo
rk\eugene_okulik\data\logs --start_date '2022-02-03 09:07:31.564'

2024-03-19 09:41 UTC, eugene-okulik reviewed
Сейчас весь поиск потработал как ожидалось
```
python analyzer2_3.py ../../eugene_okulik/data/logs/ --start_date "2022-02-03 09:01:32.360" --text WARN --unwanted_text answer
```
Этот запуск вернул одну найденную строку.  
Чисто так, чтобы всё было еще идеальнее, хорошо бы писать сообщения, соответствующие запросу. Например, если я запущу поиск так:
```
python analyzer2_3.py ../../eugene_okulik/data/logs/ --start_date "2023-02-03 09:01:32.360" 
```
В логах ничего не будет найдено, но напишет мне "Логи не содержат указанный текст." Но я текст и не искал.  
Ну и еще круто было бы в конце написать сколько строк, соответствующих условиям поиска, найдено

2024-03-20 22:19 UTC, Irina1309 commented
Добавила в код:
    if start_date or end_date:  # Проверяем, был ли указан поиск по дате
        if not results:  # Если результаты пусты, выводим сообщение
            print("С указанной датой ничего не найдено")



# Выводим количество найденных строк
    print(f"Найдено строк: {len(results)}")

2024-03-21 09:51 UTC, eugene-okulik commented
Теперь уже лучше: и количество строк показывает и про дату что-то пишет. Но всё еще пишет "Логи не содержат указанный текст." если я по тексту не искал  
Запустил так
```
python analyzer2_3.py ../../eugene_okulik/data/logs/ --start_date "2023-02-03 09:01:32.360"
```
Получил
```
Ищем текст: 'None'
Обрабатываем файл: ../../eugene_okulik/data/logs/rpe-api-error.2022-02-03.3.log
Обрабатываем файл: ../../eugene_okulik/data/logs/rpe-api-error.2022-02-03.9.log
Обрабатываем файл: ../../eugene_okulik/data/logs/rpe-api-error.2022-02-03.0.log
Обрабатываем файл: ../../eugene_okulik/data/logs/rpe-api-error.2022-02-03.5.log
Обрабатываем файл: ../../eugene_okulik/data/logs/rpe-api-error.2022-02-03.6.log
Обрабатываем файл: ../../eugene_okulik/data/logs/rpe-api-error.2022-02-03.7.log
Обрабатываем файл: ../../eugene_okulik/data/logs/rpe-api-error.2022-02-03.1.log
Обрабатываем файл: ../../eugene_okulik/data/logs/rpe-api-error.2022-02-03.2.log
Обрабатываем файл: ../../eugene_okulik/data/logs/rpe-api-error.2022-02-03.4.log
Обрабатываем файл: ../../eugene_okulik/data/logs/rpe-api-error.2022-02-03.8.log
С указанной датой ничего не найдено
Логи не содержат указанный текст.
Найдено строк: 0
```
Смущает и надпись "Ищем текст: 'None'" в начале и фраза "Логи не содержат указанный текст.". С точки зрения неподготовленного пользователя это всё еще "Какой текст? Я никакой текст и не искал."  
Можно выводить эту фразу только в случае, если текст для поиска не  None

2024-03-21 21:58 UTC, Irina1309 commented
Внесла изменения:
Если результаты пусты и была указана дата для поиска, выводится сообщение "С указанной датой ничего не найдено".
Теперь сообщение "Логи не содержат указанный текст." выводится только если был поиск по тексту.

2024-03-22 09:27 UTC, eugene-okulik requested changes
И последнее, думаю. Если мы ищем текст, которого нет в логах, то получаем очень много информации, чуть ли не всё содержимое логов, а потом сообщение, что текст не найден. Вот надо избавиться от этой кучи информации. Я уже нашел где это в коде. Нужно одну строку удалить.

2024-03-22 20:17 UTC, Irina1309 commented
Чтобы избавиться от лишней информации при поиске текста, которого нет в логах, 
удалила строку кода из функции process_log_block:
print(block_text)

Большое спасибо за подсказку.

2024-03-23 07:19 UTC, eugene-okulik approved these changes
:+1:

2024-03-23 07:19 UTC, merged