Homework_5 added new file Homework_5_list_unpack.py
eugene-okulik/IrinaA pull request #4
Opened 2024-02-17 11:29 UTC by Irina1309

2024-02-18 11:02 UTC, eugene-okulik requested changes

2024-02-18 11:02 UTC, eugene-okulik commented on homework/irina_abashidze/Homework_5/Homework_5_list_unpack.py
> +print(int(result3[-1]) + 10)
Идея в том, чтобы найти одинаковый подход к обработке каждой строки. Для этого нужно найти что-то одинаковое во всех строках: количество символов до числа разное; количество символов в числе разное. Но есть кое-что одинаковое в их структуре.

2024-02-19 14:54 UTC, eugene-okulik requested changes

2024-02-19 14:54 UTC, eugene-okulik commented on homework/irina_abashidze/Homework_5/Homework_5_list_unpack.py
> +print(int(third_result[1]) + 10)
С помощью `split` эту задачу решать правильно. Если когда-то попадется такое, так и делай.  
Но, по заданию, решить ее нужно с помощью `index` и срезов

2024-02-19 16:53 UTC, Irina1309 commented on homework/irina_abashidze/Homework_5/Homework_5_list_unpack.py
> +print(int(third_result[1]) + 10)
Поняла, спасибо, сделала с помощью index и срезов.

2024-02-19 20:02 UTC, eugene-okulik approved these changes

2024-02-19 20:02 UTC, merged